platform :ios, '7.0'

pod 'AFNetworking', '~> 2.0'
pod 'Colours', '~> 5.0'
pod 'SocketRocket', :git => 'git@github.com:tisunov/SocketRocket.git'
pod 'Mantle', '~> 1.0'
pod 'EDStarRating'
pod 'ReactiveCocoa', '~> 2.1.7'
pod 'MBProgressHUD', :git => 'https://github.com/dannybabiy/MBProgressHUD.git', :branch=>'ios7'
pod 'SLScrollViewKeyboardSupport', :git => 'https://github.com/OliverLetterer/SLScrollViewKeyboardSupport.git'
pod 'TSMessages', :git => 'https://github.com/tisunov/TSMessages.git'
pod 'Bugsnag'
pod 'ObjectiveSugar'
pod 'QuickDialog', :git => 'https://github.com/escoz/QuickDialog.git'
pod 'AKNumericFormatter', :git => 'https://github.com/blackm00n/AKNumericFormatter.git'
pod 'PaymentKit', :git => 'https://github.com/stripe/PaymentKit.git'
pod 'FCUtilities', :git => 'https://github.com/marcoarment/FCUtilities.git'
pod 'iOSBlocks', :git => 'https://github.com/dzenbot/iOSBlocks.git', :inhibit_warnings => true
pod 'UIView+AutoLayout'
pod 'PromiseKit'